import { ShiftCode, ShiftDefinition, KimperDefinition, Department } from './types';

export const DEPARTMENTS: { code: Department; name: string; description: string; color: string }[] = [
  { code: 'SERVICE', name: 'Service', description: 'Teknisi, Maintenance & Workshop Mesin', color: 'bg-blue-50 text-blue-700 border-blue-200' },
  { code: 'HSE', name: 'HSE', description: 'Health, Safety & Environment', color: 'bg-emerald-50 text-emerald-700 border-emerald-200' },
  { code: 'HRGA FA', name: 'HRGA FA', description: 'HR, General Affairs, Finance & Accounting', color: 'bg-indigo-50 text-indigo-700 border-indigo-200' },
  { code: 'PART', name: 'Part', description: 'Parts Analyst, Logistik & Storeman Gudang', color: 'bg-amber-50 text-amber-700 border-amber-200' },
];

export const SHIFTS: Record<string, ShiftDefinition> = {
  D: {
    code: 'D',
    name: 'Day Shift (D)',
    shortName: 'D (Siang)',
    timeRange: '07:00 - 15:30 WITA/WIB',
    color: 'bg-emerald-100 text-emerald-800 border-emerald-300 font-bold',
    textColor: 'text-emerald-800',
    badgeBg: 'bg-emerald-600',
    badgeBorder: 'border-emerald-700',
    description: 'Day Shift (Shift Siang)',
    isWorkday: true,
  },
  N: {
    code: 'N',
    name: 'Night Shift (N)',
    shortName: 'N (Malam)',
    timeRange: '15:30 - 23:30 WITA/WIB',
    color: 'bg-blue-100 text-blue-800 border-blue-300 font-bold',
    textColor: 'text-blue-800',
    badgeBg: 'bg-blue-600',
    badgeBorder: 'border-blue-700',
    description: 'Night Shift (Shift Malam)',
    isWorkday: true,
  },
  OFF: {
    code: 'OFF',
    name: 'Off / Libur Rutin',
    shortName: 'OFF',
    timeRange: 'Libur',
    color: 'bg-slate-100 text-slate-700 border-slate-300 font-medium',
    textColor: 'text-slate-600',
    badgeBg: 'bg-slate-400',
    badgeBorder: 'border-slate-500',
    description: 'Jadwal Libur Rutin Roster',
    isWorkday: false,
  },
  CT: {
    code: 'CT',
    name: 'Cuti (CT)',
    shortName: 'CT (Cuti)',
    timeRange: 'Hak Cuti Resmi',
    color: 'bg-amber-100 text-amber-900 border-amber-300 font-bold',
    textColor: 'text-amber-900',
    badgeBg: 'bg-amber-500',
    badgeBorder: 'border-amber-600',
    description: 'Cuti Resmi / Roster Periodik',
    isWorkday: false,
  },
  C: {
    code: 'C',
    name: 'Cuti (C)',
    shortName: 'Cuti',
    timeRange: 'Hak Cuti Resmi',
    color: 'bg-amber-100 text-amber-900 border-amber-300 font-bold',
    textColor: 'text-amber-900',
    badgeBg: 'bg-amber-500',
    badgeBorder: 'border-amber-600',
    description: 'Cuti Resmi (C)',
    isWorkday: false,
  },
  P: {
    code: 'P',
    name: 'Perjalanan Pasca Cuti (P)',
    shortName: 'P (Perjalanan)',
    timeRange: 'Pasca Cuti',
    color: 'bg-purple-100 text-purple-900 border-purple-300 font-bold',
    textColor: 'text-purple-900',
    badgeBg: 'bg-purple-600',
    badgeBorder: 'border-purple-700',
    description: 'Perjalanan Pasca Cuti (Kategori Cuti / Perjalanan Kembali ke Site)',
    isWorkday: false,
  },
  // Backward-compatibility aliases
  S1: {
    code: 'D',
    name: 'Day Shift (D)',
    shortName: 'D (Siang)',
    timeRange: '07:00 - 15:30 WITA/WIB',
    color: 'bg-emerald-100 text-emerald-800 border-emerald-300 font-bold',
    textColor: 'text-emerald-800',
    badgeBg: 'bg-emerald-600',
    badgeBorder: 'border-emerald-700',
    description: 'Day Shift',
    isWorkday: true,
  },
  S2: {
    code: 'N',
    name: 'Night Shift (N)',
    shortName: 'N (Malam)',
    timeRange: '15:30 - 23:30 WITA/WIB',
    color: 'bg-blue-100 text-blue-800 border-blue-300 font-bold',
    textColor: 'text-blue-800',
    badgeBg: 'bg-blue-600',
    badgeBorder: 'border-blue-700',
    description: 'Night Shift',
    isWorkday: true,
  },
  CUTI: {
    code: 'CT',
    name: 'Cuti (CT)',
    shortName: 'CT (Cuti)',
    timeRange: 'Hak Cuti Resmi',
    color: 'bg-amber-100 text-amber-900 border-amber-300 font-bold',
    textColor: 'text-amber-900',
    badgeBg: 'bg-amber-500',
    badgeBorder: 'border-amber-600',
    description: 'Cuti Resmi',
    isWorkday: false,
  },
  PERJALANAN: {
    code: 'P',
    name: 'Perjalanan Pasca Cuti (P)',
    shortName: 'P (Perjalanan)',
    timeRange: 'Pasca Cuti',
    color: 'bg-purple-100 text-purple-900 border-purple-300 font-bold',
    textColor: 'text-purple-900',
    badgeBg: 'bg-purple-600',
    badgeBorder: 'border-purple-700',
    description: 'Perjalanan Pasca Cuti (Kategori Cuti)',
    isWorkday: false,
  },
  IZIN: {
    code: 'P',
    name: 'Perjalanan Pasca Cuti (P)',
    shortName: 'P (Perjalanan)',
    timeRange: 'Pasca Cuti',
    color: 'bg-purple-100 text-purple-900 border-purple-300 font-bold',
    textColor: 'text-purple-900',
    badgeBg: 'bg-purple-600',
    badgeBorder: 'border-purple-700',
    description: 'Perjalanan Pasca Cuti (Kategori Cuti)',
    isWorkday: false,
  },
};

export const MONTH_NAMES_ID = [
  'Januari',
  'Februari',
  'Maret',
  'April',
  'Mei',
  'Juni',
  'Juli',
  'Agustus',
  'September',
  'Oktober',
  'November',
  'Desember',
];

export const DAY_NAMES_ID = ['Minggu', 'Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu'];
export const DAY_SHORT_NAMES_ID = ['Min', 'Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab'];

export const KIMPER_LIST: KimperDefinition[] = [
  {
    code: 'LV',
    name: 'Light Vehicle',
    category: 'Kendaraan Sarana',
    description: 'Izin mengemudikan kendaraan roda 4 sarana operasional tambang/workshop',
    color: 'bg-amber-50 text-amber-900 border-amber-300',
    badgeBg: 'bg-amber-500',
    textColor: 'text-amber-900',
    borderColor: 'border-amber-400',
    minRecommendedPerShift: 1,
  },
  {
    code: 'FORKLIFT',
    name: 'Forklift Operator',
    category: 'Alat Angkut Material',
    description: 'Izin operator unit forklift untuk handling komponen dan material sparepart',
    color: 'bg-emerald-50 text-emerald-800 border-emerald-300',
    badgeBg: 'bg-emerald-600',
    textColor: 'text-emerald-800',
    borderColor: 'border-emerald-400',
    minRecommendedPerShift: 1,
  },
  {
    code: 'WAH',
    name: 'Working At Height',
    category: 'Keselamatan Ketinggian',
    description: 'Izin bekerja di ketinggian (Working At Height) untuk perawatan unit tinggi',
    color: 'bg-sky-50 text-sky-800 border-sky-300',
    badgeBg: 'bg-sky-600',
    textColor: 'text-sky-800',
    borderColor: 'border-sky-400',
    minRecommendedPerShift: 1,
  },
  {
    code: 'OHC',
    name: 'Overhead Crane',
    category: 'Alat Angkat Workshop',
    description: 'Izin operator derek gantung (Overhead Crane) untuk bongkar pasang komponen berat',
    color: 'bg-purple-50 text-purple-800 border-purple-300',
    badgeBg: 'bg-purple-600',
    textColor: 'text-purple-800',
    borderColor: 'border-purple-400',
    minRecommendedPerShift: 1,
  },
  {
    code: 'RIGGER',
    name: 'Rigger Bersertifikat',
    category: 'Juru Ikat Beban',
    description: 'Izin juru ikat beban & pemberi aba-aba pemindahan komponen dengan crane',
    color: 'bg-indigo-50 text-indigo-800 border-indigo-300',
    badgeBg: 'bg-indigo-600',
    textColor: 'text-indigo-800',
    borderColor: 'border-indigo-400',
    minRecommendedPerShift: 1,
  },
  {
    code: 'MANLIFT',
    name: 'Manlift / Boomlift',
    category: 'Alat Ketinggian',
    description: 'Izin pengoperasian sarana keranjang ketinggian (Boomlift / Scissor Lift)',
    color: 'bg-blue-50 text-blue-800 border-blue-300',
    badgeBg: 'bg-blue-600',
    textColor: 'text-blue-800',
    borderColor: 'border-blue-400',
    minRecommendedPerShift: 0,
  },
  {
    code: 'WELDING',
    name: 'Hotwork / Welding',
    category: 'Pengelasan & Fabrikasi',
    description: 'Izin khusus pekerjaan panas (Hotwork), pengelasan & modifikasi struktur',
    color: 'bg-rose-50 text-rose-800 border-rose-300',
    badgeBg: 'bg-rose-600',
    textColor: 'text-rose-800',
    borderColor: 'border-rose-400',
    minRecommendedPerShift: 0,
  },
];

export const KIMPER_MAP: Record<string, KimperDefinition> = KIMPER_LIST.reduce(
  (acc, k) => {
    acc[k.code] = k;
    // Also handle case insensitivity like 'Forklift' -> 'FORKLIFT'
    acc[k.code.toUpperCase()] = k;
    return acc;
  },
  {} as Record<string, KimperDefinition>
);
// Also alias lowercase / titlecase
KIMPER_MAP['Forklift'] = KIMPER_MAP['FORKLIFT'];
KIMPER_MAP['Manlift'] = KIMPER_MAP['MANLIFT'];
KIMPER_MAP['Welding'] = KIMPER_MAP['WELDING'];

